### PR TITLE
I have merged with the upstream version, and updated the title of documentation page for uploading an entityID to the persistence Store

### PR DESCRIPTION
**Pull request by pruvostc**
I have merged with the upstream version, and updated the title of documentation page for uploading an entityID to the persistence Store

Change-Id: I60530bd133ffd61e11cf617d8f6d691f7fb4ff7c

### CODE REVIEW

**Comment by leifj** [comment]
I only see changes to package.json and package-lock.json. That doesn't seem right...

**Comment by pruvostc** [comment]
Indeed, let me check…


Best regards,
Christian.

**Comment by pruvostc** [comment]
Ah, the change was committed, but not pushed... done now.

**Comment by leifj** [comment]
ok but then I don't understand why there are changes to package and package-lock - those should be unchanged by the doc update.

**Comment by pruvostc** [comment]
I had actually updated my forked version from the upstream version. that is why these 2 JSON files were changed.

**Comment by leifj** [comment]
yeah but once you have merged master into your branch those diffs should disappear... unless you've actually changed the files

**Pull request merged**
